### ISSUE TITLE
Escaping

### ISSUE THREAD

**Issue by lydell** [jonschlinkert/html-tag#1]
```js
const tag = require("html-tag")

console.log(tag("<script>alert(1337)</script>"))
console.log(tag("div", {"><script>alert(1337)</script>": true}))
console.log(tag("div", {id: '"><script>alert(1337)</script>'}))
console.log(tag("div", {}, "<script>alert(1337)</script>"))
```
```
<<script>alert(1337)</script>></<script>alert(1337)</script>>
<div ><script>alert(1337)</script>></div>
<div id=""><script>alert(1337)</script>"></div>
<div><script>alert(1337)</script></div>
```

I’d expect tag names, attribute names, attribute values and text to be escaped according to their respective rules in the HTML standard, to make the user safe from XSS.

**Comment by jonschlinkert** [comment]
This seems like something you should do before or after passing values to this library.

**Comment by lydell** [comment]
I see! This package is not for me, then. Might be worth mentioning your escaping advice in the readme.
